title: Vincent Harlius
description: Machine Learning Engineer
theme: jekyll-theme-minimal
logo: NewIm.jpg

# These variables must match the names used in the HTML file above
email: "lvharlius.vh74@gmail.com"
phone: "+62 811 8090 901"
about_me: "A passionate Intelligent System Engineer focusing on Advancement of AI especially on Edge AI for Embedded system"
